pipeline {
    agent any
    tools {
        maven 'Maven3'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                dir('starter') {
                    sh 'mvn -B clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir('starter') {
                    sh 'mvn -B test'
                }
            }
            post {
                always {
                    dir('starter') {
                        junit 'target/surefire-reports/*.xml'
                    }
                    
                }
            }
        }
        stage('Archive') {
            steps {
                dir('starter') {
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
                
            }
        }
    }
}
